swagger: "2.0"
info:
  title: ""
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /modules/meta:
    get:
      tags:
      - modules
      summary: meta modules
      operationId: modules#meta
      responses:
        "200":
          description: OK response.
          schema: {}
      schemes:
      - http
  /projects/{id}/activity:
    get:
      tags:
      - activity
      summary: project activity
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: activity#project
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ActivityProjectResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/follow:
    post:
      tags:
      - following
      summary: follow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#follow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingFollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/followers:
    get:
      tags:
      - following
      summary: followers following
      operationId: following#followers
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FollowingFollowersResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingFollowersUnauthorizedResponseBody'
      schemes:
      - http
  /projects/{id}/unfollow:
    post:
      tags:
      - following
      summary: unfollow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#unfollow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingUnfollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/update:
    post:
      tags:
      - project
      summary: update project
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: project#update
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ProjectUpdateRequestBody'
          required:
          - body
      responses:
        "200":
          description: OK response.
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /stations/{id}/activity:
    get:
      tags:
      - activity
      summary: station activity
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: activity#station
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ActivityStationResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/devices/{deviceId}/refresh:
    post:
      tags:
      - tasks
      summary: refresh device tasks
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: tasks#refresh device
      parameters:
      - name: deviceId
        in: path
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksRefreshDeviceUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/five:
    get:
      tags:
      - tasks
      summary: five tasks
      operationId: tasks#five
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksFiveUnauthorizedResponseBody'
      schemes:
      - http
  /test/{id}:
    get:
      tags:
      - test
      summary: get test
      operationId: test#get
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestGetUnauthorizedResponseBody'
      schemes:
      - http
  /test/email:
    get:
      tags:
      - test
      summary: email test
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: test#email
      parameters:
      - name: address
        in: query
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestEmailUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /test/error:
    get:
      tags:
      - test
      summary: error test
      operationId: test#error
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestErrorUnauthorizedResponseBody'
      schemes:
      - http
definitions:
  ActivityEntryResponseBody:
    title: 'Mediatype identifier: application/vnd.app.activity.entry; view=default'
    type: object
    properties:
      created_at:
        type: integer
        example: 7547285348525734610
        format: int64
      id:
        type: integer
        example: 4759091417389918951
        format: int64
      meta:
        example: Perspiciatis omnis commodi tempora ut officia.
      project:
        $ref: '#/definitions/ProjectSummaryResponseBody'
      station:
        $ref: '#/definitions/StationSummaryResponseBody'
      type:
        type: string
        example: Neque ea alias.
    description: ActivityEntryResponseBody result type (default view)
    example:
      created_at: 6269895511753342887
      id: 7514638001280817070
      meta: Eos et occaecati molestiae aliquid explicabo.
      project:
        id: 3154713732921053033
        name: Occaecati et perferendis.
      station:
        id: 3749521312036636972
        name: Ipsam corrupti ea dolorum.
      type: Ut in.
    required:
    - id
    - project
    - station
    - created_at
    - type
    - meta
  ActivityEntryResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.app.activity.entry; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/ActivityEntryResponseBody'
    description: ActivityEntryCollectionResponseBody is the result type for an array
      of ActivityEntryResponseBody (default view)
    example:
    - created_at: 1472691811713346493
      id: 6214483488355277271
      meta: Vel aut accusantium.
      project:
        id: 3154713732921053033
        name: Occaecati et perferendis.
      station:
        id: 3749521312036636972
        name: Ipsam corrupti ea dolorum.
      type: Beatae magni aliquam perferendis facilis.
    - created_at: 1472691811713346493
      id: 6214483488355277271
      meta: Vel aut accusantium.
      project:
        id: 3154713732921053033
        name: Occaecati et perferendis.
      station:
        id: 3749521312036636972
        name: Ipsam corrupti ea dolorum.
      type: Beatae magni aliquam perferendis facilis.
    - created_at: 1472691811713346493
      id: 6214483488355277271
      meta: Vel aut accusantium.
      project:
        id: 3154713732921053033
        name: Occaecati et perferendis.
      station:
        id: 3749521312036636972
        name: Ipsam corrupti ea dolorum.
      type: Beatae magni aliquam perferendis facilis.
  ActivityProjectResponseBody:
    title: 'Mediatype identifier: application/vnd.app.project.activity.page; view=default'
    type: object
    properties:
      activities:
        $ref: '#/definitions/ActivityEntryResponseBodyCollection'
      page:
        type: integer
        example: 1747552566
        format: int32
      total:
        type: integer
        example: 573679883
        format: int32
    description: ProjectResponseBody result type (default view)
    example:
      activities:
      - created_at: 1472691811713346493
        id: 6214483488355277271
        meta: Vel aut accusantium.
        project:
          id: 3154713732921053033
          name: Occaecati et perferendis.
        station:
          id: 3749521312036636972
          name: Ipsam corrupti ea dolorum.
        type: Beatae magni aliquam perferendis facilis.
      - created_at: 1472691811713346493
        id: 6214483488355277271
        meta: Vel aut accusantium.
        project:
          id: 3154713732921053033
          name: Occaecati et perferendis.
        station:
          id: 3749521312036636972
          name: Ipsam corrupti ea dolorum.
        type: Beatae magni aliquam perferendis facilis.
      - created_at: 1472691811713346493
        id: 6214483488355277271
        meta: Vel aut accusantium.
        project:
          id: 3154713732921053033
          name: Occaecati et perferendis.
        station:
          id: 3749521312036636972
          name: Ipsam corrupti ea dolorum.
        type: Beatae magni aliquam perferendis facilis.
      page: 442176392
      total: 1279096242
    required:
    - activities
    - total
    - page
  ActivityStationResponseBody:
    title: 'Mediatype identifier: application/vnd.app.station.activity.page; view=default'
    type: object
    properties:
      activities:
        $ref: '#/definitions/ActivityEntryResponseBodyCollection'
      page:
        type: integer
        example: 2109351194
        format: int32
      total:
        type: integer
        example: 566393622
        format: int32
    description: StationResponseBody result type (default view)
    example:
      activities:
      - created_at: 1472691811713346493
        id: 6214483488355277271
        meta: Vel aut accusantium.
        project:
          id: 3154713732921053033
          name: Occaecati et perferendis.
        station:
          id: 3749521312036636972
          name: Ipsam corrupti ea dolorum.
        type: Beatae magni aliquam perferendis facilis.
      - created_at: 1472691811713346493
        id: 6214483488355277271
        meta: Vel aut accusantium.
        project:
          id: 3154713732921053033
          name: Occaecati et perferendis.
        station:
          id: 3749521312036636972
          name: Ipsam corrupti ea dolorum.
        type: Beatae magni aliquam perferendis facilis.
      - created_at: 1472691811713346493
        id: 6214483488355277271
        meta: Vel aut accusantium.
        project:
          id: 3154713732921053033
          name: Occaecati et perferendis.
        station:
          id: 3749521312036636972
          name: Ipsam corrupti ea dolorum.
        type: Beatae magni aliquam perferendis facilis.
      page: 763468930
      total: 2057958577
    required:
    - activities
    - total
    - page
  AvatarResponseBody:
    title: AvatarResponseBody
    type: object
    properties:
      url:
        type: string
        example: Illo iusto modi magni beatae.
    example:
      url: Sed recusandae molestiae magni vitae dolorem numquam.
    required:
    - url
  FollowerResponseBody:
    title: 'Mediatype identifier: application/vnd.app.follower; view=default'
    type: object
    properties:
      avatar:
        $ref: '#/definitions/AvatarResponseBody'
      id:
        type: integer
        example: 224892259121824166
        format: int64
      name:
        type: string
        example: Deserunt est doloribus.
    description: FollowerResponseBody result type (default view)
    example:
      avatar:
        url: Non sed a nostrum.
      id: 7134691977437916367
      name: Voluptas voluptatem ut aut repellat et unde.
    required:
    - id
    - name
  FollowerResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.app.follower; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/FollowerResponseBody'
    description: FollowerCollectionResponseBody is the result type for an array of
      FollowerResponseBody (default view)
    example:
    - avatar:
        url: Non sed a nostrum.
      id: 2034953970000477736
      name: Facilis architecto sed.
    - avatar:
        url: Non sed a nostrum.
      id: 2034953970000477736
      name: Facilis architecto sed.
    - avatar:
        url: Non sed a nostrum.
      id: 2034953970000477736
      name: Facilis architecto sed.
    - avatar:
        url: Non sed a nostrum.
      id: 2034953970000477736
      name: Facilis architecto sed.
  FollowingFollowUnauthorizedResponseBody:
    title: FollowingFollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Velit quaerat ut nesciunt ut et.
  FollowingFollowersResponseBody:
    title: 'Mediatype identifier: application/vnd.app.followers; view=default'
    type: object
    properties:
      followers:
        $ref: '#/definitions/FollowerResponseBodyCollection'
      page:
        type: integer
        example: 472072992
        format: int32
      total:
        type: integer
        example: 243973931
        format: int32
    description: FollowersResponseBody result type (default view)
    example:
      followers:
      - avatar:
          url: Non sed a nostrum.
        id: 2034953970000477736
        name: Facilis architecto sed.
      - avatar:
          url: Non sed a nostrum.
        id: 2034953970000477736
        name: Facilis architecto sed.
      page: 1813364595
      total: 1646485548
    required:
    - followers
    - total
    - page
  FollowingFollowersUnauthorizedResponseBody:
    title: FollowingFollowersUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Quod autem ut illum et.
  FollowingUnfollowUnauthorizedResponseBody:
    title: FollowingUnfollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Veniam vel nisi placeat ad.
  ProjectSummaryResponseBody:
    title: ProjectSummaryResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 1972138218893876778
        format: int64
      name:
        type: string
        example: Ipsam non vitae neque vitae non.
    example:
      id: 6966341089960532853
      name: Earum perspiciatis at.
    required:
    - id
    - name
  ProjectUpdateRequestBody:
    title: ProjectUpdateRequestBody
    type: object
    properties:
      body:
        type: string
        example: Sint quasi possimus et.
    example:
      body: Quibusdam sunt quis rerum deleniti.
    required:
    - body
  StationSummaryResponseBody:
    title: StationSummaryResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 2786782174333546569
        format: int64
      name:
        type: string
        example: Consequatur at amet.
    example:
      id: 6395964898701089048
      name: In aliquam suscipit voluptatibus iure.
    required:
    - id
    - name
  TasksFiveUnauthorizedResponseBody:
    title: TasksFiveUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Animi consequuntur qui.
  TasksRefreshDeviceUnauthorizedResponseBody:
    title: TasksRefreshDeviceUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Sit quis fuga est magnam facilis aut.
  TestEmailUnauthorizedResponseBody:
    title: TestEmailUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Officia explicabo reprehenderit quia et voluptas.
  TestErrorUnauthorizedResponseBody:
    title: TestErrorUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Recusandae fuga quia libero.
  TestGetUnauthorizedResponseBody:
    title: TestGetUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Maiores sint sit in vel alias est.
securityDefinitions:
  jwt_header_Authorization:
    type: apiKey
    description: |2-

      **Security Scopes**:
        * `api:access`: API access
        * `api:admin`: API admin access
        * `api:ingestion`: Ingestion access
    name: Authorization
    in: header
