swagger: "2.0"
info:
  title: ""
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /modules/meta:
    get:
      tags:
      - modules
      summary: meta modules
      operationId: modules#meta
      responses:
        "200":
          description: OK response.
          schema: {}
      schemes:
      - http
  /projects/{id}/follow:
    post:
      tags:
      - following
      summary: follow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#follow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingFollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/unfollow:
    post:
      tags:
      - following
      summary: unfollow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#unfollow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingUnfollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/devices/{deviceId}/refresh:
    post:
      tags:
      - tasks
      summary: refresh device tasks
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: tasks#refresh device
      parameters:
      - name: deviceId
        in: path
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksRefreshDeviceUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/five:
    get:
      tags:
      - tasks
      summary: five tasks
      operationId: tasks#five
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksFiveUnauthorizedResponseBody'
      schemes:
      - http
  /test/{id}:
    get:
      tags:
      - test
      summary: get test
      operationId: test#get
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestGetUnauthorizedResponseBody'
      schemes:
      - http
  /test/email:
    get:
      tags:
      - test
      summary: email test
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: test#email
      parameters:
      - name: address
        in: query
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestEmailUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /test/error:
    get:
      tags:
      - test
      summary: error test
      operationId: test#error
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestErrorUnauthorizedResponseBody'
      schemes:
      - http
definitions:
  FollowingFollowUnauthorizedResponseBody:
    title: FollowingFollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: A ut exercitationem voluptatibus modi veniam.
  FollowingUnfollowUnauthorizedResponseBody:
    title: FollowingUnfollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Impedit necessitatibus et expedita.
  TasksFiveUnauthorizedResponseBody:
    title: TasksFiveUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Similique minima quas aspernatur fuga molestiae.
  TasksRefreshDeviceUnauthorizedResponseBody:
    title: TasksRefreshDeviceUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Molestiae reiciendis quia porro voluptatibus non.
  TestEmailUnauthorizedResponseBody:
    title: TestEmailUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Molestiae ipsam cupiditate sapiente at totam dignissimos.
  TestErrorUnauthorizedResponseBody:
    title: TestErrorUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Aut eaque ipsa unde quia qui.
  TestGetUnauthorizedResponseBody:
    title: TestGetUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Eius beatae.
securityDefinitions:
  jwt_header_Authorization:
    type: apiKey
    description: |2-

      **Security Scopes**:
        * `api:access`: API access
        * `api:admin`: API admin access
        * `api:ingestion`: Ingestion access
    name: Authorization
    in: header
