swagger: "2.0"
info:
  title: ""
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /modules/meta:
    get:
      tags:
      - modules
      summary: meta modules
      operationId: modules#meta
      responses:
        "200":
          description: OK response.
          schema: {}
      schemes:
      - http
  /projects/{id}/activity:
    get:
      tags:
      - activity
      summary: project activity
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: activity#project
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ActivityProjectResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/follow:
    post:
      tags:
      - following
      summary: follow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#follow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingFollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/followers:
    get:
      tags:
      - following
      summary: followers following
      operationId: following#followers
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FollowingFollowersResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingFollowersUnauthorizedResponseBody'
      schemes:
      - http
  /projects/{id}/unfollow:
    post:
      tags:
      - following
      summary: unfollow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#unfollow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingUnfollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /stations/{id}/activity:
    get:
      tags:
      - activity
      summary: station activity
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: activity#station
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ActivityStationResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/devices/{deviceId}/refresh:
    post:
      tags:
      - tasks
      summary: refresh device tasks
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: tasks#refresh device
      parameters:
      - name: deviceId
        in: path
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksRefreshDeviceUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/five:
    get:
      tags:
      - tasks
      summary: five tasks
      operationId: tasks#five
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksFiveUnauthorizedResponseBody'
      schemes:
      - http
  /test/{id}:
    get:
      tags:
      - test
      summary: get test
      operationId: test#get
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestGetUnauthorizedResponseBody'
      schemes:
      - http
  /test/email:
    get:
      tags:
      - test
      summary: email test
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: test#email
      parameters:
      - name: address
        in: query
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestEmailUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /test/error:
    get:
      tags:
      - test
      summary: error test
      operationId: test#error
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestErrorUnauthorizedResponseBody'
      schemes:
      - http
definitions:
  ActivityEntryResponseBody:
    title: 'Mediatype identifier: application/vnd.app.activity.entry; view=default'
    type: object
    properties:
      created_at:
        type: integer
        example: 3468908841579358006
        format: int64
      id:
        type: integer
        example: 3072237865390360984
        format: int64
      meta:
        example: Vitae non qui dolore earum perspiciatis.
      project:
        $ref: '#/definitions/ProjectSummaryResponseBody'
      station:
        $ref: '#/definitions/StationSummaryResponseBody'
      type:
        type: string
        example: Non vitae.
    description: ActivityEntryResponseBody result type (default view)
    example:
      created_at: 2786782174333546569
      id: 7332078300190363827
      meta: Quibusdam in.
      project:
        id: 7436001330053072599
        name: Sint aut modi.
      station:
        id: 8912933545598277937
        name: Provident dolor dolorum et.
      type: Consequatur at amet.
    required:
    - id
    - project
    - station
    - created_at
    - type
    - meta
  ActivityEntryResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.app.activity.entry; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/ActivityEntryResponseBody'
    description: ActivityEntryCollectionResponseBody is the result type for an array
      of ActivityEntryResponseBody (default view)
    example:
    - created_at: 5486421500064581089
      id: 3326745769059566974
      meta: Occaecati et perferendis.
      project:
        id: 7436001330053072599
        name: Sint aut modi.
      station:
        id: 8912933545598277937
        name: Provident dolor dolorum et.
      type: Consequatur architecto optio est fugit quos sed.
    - created_at: 5486421500064581089
      id: 3326745769059566974
      meta: Occaecati et perferendis.
      project:
        id: 7436001330053072599
        name: Sint aut modi.
      station:
        id: 8912933545598277937
        name: Provident dolor dolorum et.
      type: Consequatur architecto optio est fugit quos sed.
    - created_at: 5486421500064581089
      id: 3326745769059566974
      meta: Occaecati et perferendis.
      project:
        id: 7436001330053072599
        name: Sint aut modi.
      station:
        id: 8912933545598277937
        name: Provident dolor dolorum et.
      type: Consequatur architecto optio est fugit quos sed.
    - created_at: 5486421500064581089
      id: 3326745769059566974
      meta: Occaecati et perferendis.
      project:
        id: 7436001330053072599
        name: Sint aut modi.
      station:
        id: 8912933545598277937
        name: Provident dolor dolorum et.
      type: Consequatur architecto optio est fugit quos sed.
  ActivityProjectResponseBody:
    title: 'Mediatype identifier: application/vnd.app.project.activity.page; view=default'
    type: object
    properties:
      activities:
        $ref: '#/definitions/ActivityEntryResponseBodyCollection'
      page:
        type: integer
        example: 729491107
        format: int32
      total:
        type: integer
        example: 1990057909
        format: int32
    description: ProjectResponseBody result type (default view)
    example:
      activities:
      - created_at: 5486421500064581089
        id: 3326745769059566974
        meta: Occaecati et perferendis.
        project:
          id: 7436001330053072599
          name: Sint aut modi.
        station:
          id: 8912933545598277937
          name: Provident dolor dolorum et.
        type: Consequatur architecto optio est fugit quos sed.
      - created_at: 5486421500064581089
        id: 3326745769059566974
        meta: Occaecati et perferendis.
        project:
          id: 7436001330053072599
          name: Sint aut modi.
        station:
          id: 8912933545598277937
          name: Provident dolor dolorum et.
        type: Consequatur architecto optio est fugit quos sed.
      page: 1671298209
      total: 711077855
    required:
    - activities
    - total
    - page
  ActivityStationResponseBody:
    title: 'Mediatype identifier: application/vnd.app.station.activity.page; view=default'
    type: object
    properties:
      activities:
        $ref: '#/definitions/ActivityEntryResponseBodyCollection'
      page:
        type: integer
        example: 1772861818
        format: int32
      total:
        type: integer
        example: 1062094643
        format: int32
    description: StationResponseBody result type (default view)
    example:
      activities:
      - created_at: 5486421500064581089
        id: 3326745769059566974
        meta: Occaecati et perferendis.
        project:
          id: 7436001330053072599
          name: Sint aut modi.
        station:
          id: 8912933545598277937
          name: Provident dolor dolorum et.
        type: Consequatur architecto optio est fugit quos sed.
      - created_at: 5486421500064581089
        id: 3326745769059566974
        meta: Occaecati et perferendis.
        project:
          id: 7436001330053072599
          name: Sint aut modi.
        station:
          id: 8912933545598277937
          name: Provident dolor dolorum et.
        type: Consequatur architecto optio est fugit quos sed.
      page: 1757239305
      total: 1185743574
    required:
    - activities
    - total
    - page
  AvatarResponseBody:
    title: AvatarResponseBody
    type: object
    properties:
      url:
        type: string
        example: Ipsum sit itaque rerum.
    example:
      url: Ad in cumque aut sit velit.
    required:
    - url
  FollowerResponseBody:
    title: 'Mediatype identifier: application/vnd.app.follower; view=default'
    type: object
    properties:
      avatar:
        $ref: '#/definitions/AvatarResponseBody'
      id:
        type: integer
        example: 4679635549788073785
        format: int64
      name:
        type: string
        example: Molestiae aliquid.
    description: FollowerResponseBody result type (default view)
    example:
      avatar:
        url: Perspiciatis doloremque.
      id: 3725013081908955775
      name: Nesciunt ut et.
    required:
    - id
    - name
  FollowerResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.app.follower; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/FollowerResponseBody'
    description: FollowerCollectionResponseBody is the result type for an array of
      FollowerResponseBody (default view)
    example:
    - avatar:
        url: Perspiciatis doloremque.
      id: 8944683791525516609
      name: Aut amet.
    - avatar:
        url: Perspiciatis doloremque.
      id: 8944683791525516609
      name: Aut amet.
    - avatar:
        url: Perspiciatis doloremque.
      id: 8944683791525516609
      name: Aut amet.
  FollowingFollowUnauthorizedResponseBody:
    title: FollowingFollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Perspiciatis omnis commodi tempora ut officia.
  FollowingFollowersResponseBody:
    title: 'Mediatype identifier: application/vnd.app.followers; view=default'
    type: object
    properties:
      followers:
        $ref: '#/definitions/FollowerResponseBodyCollection'
      page:
        type: integer
        example: 193027135
        format: int32
      total:
        type: integer
        example: 972399850
        format: int32
    description: FollowersResponseBody result type (default view)
    example:
      followers:
      - avatar:
          url: Perspiciatis doloremque.
        id: 8944683791525516609
        name: Aut amet.
      - avatar:
          url: Perspiciatis doloremque.
        id: 8944683791525516609
        name: Aut amet.
      page: 1712760879
      total: 1593962380
    required:
    - followers
    - total
    - page
  FollowingFollowersUnauthorizedResponseBody:
    title: FollowingFollowersUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Reprehenderit sit deserunt est doloribus accusamus illo.
  FollowingUnfollowUnauthorizedResponseBody:
    title: FollowingUnfollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Numquam commodi ut in natus eos.
  ProjectSummaryResponseBody:
    title: ProjectSummaryResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 6433030965608229216
        format: int64
      name:
        type: string
        example: Consequatur aliquam dignissimos quia.
    example:
      id: 6004395135312033861
      name: Quia omnis fugiat.
    required:
    - id
    - name
  StationSummaryResponseBody:
    title: StationSummaryResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 3004401495262376821
        format: int64
      name:
        type: string
        example: Facere repellat ut.
    example:
      id: 7577586275964425592
      name: Labore consequatur accusantium dolor totam dolores.
    required:
    - id
    - name
  TasksFiveUnauthorizedResponseBody:
    title: TasksFiveUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Modi magni beatae animi sed.
  TasksRefreshDeviceUnauthorizedResponseBody:
    title: TasksRefreshDeviceUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Molestiae magni vitae.
  TestEmailUnauthorizedResponseBody:
    title: TestEmailUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Omnis id.
  TestErrorUnauthorizedResponseBody:
    title: TestErrorUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Et unde omnis maiores.
  TestGetUnauthorizedResponseBody:
    title: TestGetUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Numquam et tempora voluptas voluptatem ut aut.
securityDefinitions:
  jwt_header_Authorization:
    type: apiKey
    description: |2-

      **Security Scopes**:
        * `api:access`: API access
        * `api:admin`: API admin access
        * `api:ingestion`: Ingestion access
    name: Authorization
    in: header
