steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'server-build', '.']
  dir: 'server'
  id: 'server'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'admin-build', '.']
  dir: 'admin'
  waitFor: ['-']
  id: 'admin'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'frontend-build', '.']
  dir: 'frontend'
  waitFor: ['-']
  id: 'frontend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'landing-build', '.']
  dir: 'landing'
  waitFor: ['-']
  id: 'landing'

- name: 'alpine'
  args: ['mkdir', '-p', '/workspace/build']
  waitFor: ['-']
  id: 'build-dir'

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace/build:/build', 'server-build', 'sh', '-c', 'cp -r /go/bin/server /build/ && mkdir /build/api && cp -r api/public /build/api/']
  waitFor: ['build-dir', 'server']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace/build:/build', 'admin-build', 'sh', '-c', 'cp -r /usr/app/build /build/admin']
  waitFor: ['build-dir', 'admin']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace/build:/build', 'frontend-build', 'sh', '-c', 'cp -r /usr/app/build /build/frontend']
  waitFor: ['build-dir', 'frontend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace/build:/build', 'landing-build', 'sh', '-c', 'cp -r /usr/app/build /build/landing']
  waitFor: ['build-dir', 'landing']
