version: '2'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: server -a :8080 -backend-url postgres://fieldkit:password@postgres/fieldkit?sslmode=disable
    restart: always
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=fieldkit
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fieldkit
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/:ro
