version: '2'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: server
    restart: always
    env_file:
      - fieldkit.env
    environment:
      - FIELDKIT_ADDR=:8080
      - FIELDKIT_POSTGRES_URL=postgres://fieldkit:password@postgres/fieldkit?sslmode=disable
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    depends_on:
      - postgres
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
  postgres:
    image: mdillon/postgis:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fieldkit
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fieldkit
    volumes:
      - ./active-schema:/docker-entrypoint-initdb.d/:ro
