version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    command: fieldkit -a :8080 -backend-url postgres://fieldkit:password@postgres/fieldkit?sslmode=disable -session-store-address redis:6379 --invite
    restart: always
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=fieldkit
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fieldkit
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/:ro
